### ISSUE TITLE
Using wrong version of phaser-tiled

### ISSUE THREAD

**Issue by contextlimit** [englercj/lttp-phaser#3]
In the package.json it references `2.0.0`, but the build is being generated with gulp, which I believe is set to `^1.2.1`. I've got them side-by-side and they don't match.

PS. I'd like to help but I feel like there's a lot more moving parts than I would expect for a simple game. Don't get me wrong, LTTP and phaser-tiled are cool, but there seems to be some strange barriers to helping. 1) LESS. There's almost no CSS. Why? 2) EJS. There's almost no HTML. Why? 3) Gulp _and_ webpack? I don't get it. 4) Inheriting Phaser classes makes it difficult to reason where things happening, in LTTP or in Phaser. 5) TypeScript - already a big step, and many JS devs will not bother with non-raw JS libraries, and the gains are questionable here - outside of the core game engine.

**Comment by contextlimit** [comment]
Seems like that's the map asset packer, nevermind. Still getting my head around this please bare with me.

**Comment by englercj** [comment]
> 1) LESS. There's almost no CSS. Why?

Why not? webpack and npm do all of this for you, you shouldn't even notice it is less. imports, and variables is basically why.

> 2) EJS. There's almost no HTML. Why?

Because we inject values into it during webpack build. This is done by compiling the ejs and inserting the bundles who's names are not preknown.

> 3) Gulp and webpack? I don't get it.

Webpack builds the bundle js file, but there is more to the build than that. We need to build asset packs for the maps, lint the code, watch for changes on all things (not just bundle js), etc.

> 4) Inheriting Phaser classes makes it difficult to reason where things happening, in LTTP or in Phaser.

Not sure I understand what you are saying here.

> TypeScript - already a big step, and many JS devs will not bother with non-raw JS libraries, and the gains are questionable here - outside of the core game engine.

Typescript is used as ES6 + types here. If no typescript was used, the code would look nearly identical since it would be ES6. I'm not worried about adoption or getting other devs on-board. I'm just building something I find fun to work on.
