### ISSUE TITLE
Controls?

### ISSUE THREAD

**Issue by archae0pteryx** [englercj/lttp-phaser#6]
I'm not familiar with Phaser... I guess I need to get there.In the meantime,  will you point me in the right direction for modifing the controls? F. N. Love it though mate. Really. You're missing a ; in math.ts

Cheers

**Comment by englercj** [comment]
In this game the level binds the user input and dispatches it to the player as events, this is because of how I unload and load worlds as you "zone" to different maps.

In the base level you can see where I map actions to keys:

https://github.com/englercj/lttp/blob/master/src/levels/Level.ts#L35-L64

and where I handle keyboard input:

https://github.com/englercj/lttp/blob/master/src/levels/Level.ts#L300

Keyboard input (and others) are bound here in the BaseState class, which Level inherits from:

https://github.com/englercj/lttp/blob/master/src/states/GameState.ts#L24

Hope this helps! Feel free to put in PRs, I don't have time to work on this much these days.

**Comment by archae0pteryx** [comment]
Awesome thanks for your help!
